GameHome/urls.py
from django.urls import path
from GameHome import views

app_name = 'GameHome'

urlpatterns = [
    path('', views.index, name='index'),
    path('dang-nhap/', views.login, name='login'),
    path('dang-ky/', views.register, name='register'),
    path('gioi-thieu/', views.review, name='review'),
    path('tro-choi/', views.games, name='games'),
    path('tin-tuc/', views.blog, name='blog'),
    path('lien-he/', views.contact, name='contact'),
    path('quen-mat-khau/', views.forgetpassword, name='forgetpassword')
]

typinggame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GameHome.urls')),

]

GameHome/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    accountid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(null=True)
    createdate  = models.DateField(auto_now_add=True, blank=True, null=True)
    editdate = models.DateTimeField(auto_now=True, blank=True, null=True)
    isenable = models.BooleanField(default=True, blank=True, null=True)

    def __str__(self):
        return self.username
    
    class Meta:
        managed = True
        db_table = 'Account'

class Game(models.Model):
    gameid = models.AutoField(primary_key=True)
    gameorder = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    createdate  = models.DateField(auto_now_add=True, blank=True, null=True)
    editdate = models.DateTimeField(auto_now=True, blank=True, null=True)
    isenable = models.BooleanField(default=True, blank=True, null=True)
    note = models.TextField(max_length=250, blank=True, null=True)

    tracking = models.ManyToManyField(Account)

    def __str__(self):
        return self.title
    
    class Meta:
        managed = True
        db_table = 'Game'

GameHome/views.py
from django.shortcuts import render, redirect
from typinggame.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from .models import *
import random

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

def review(request):
    return render(request, 'homepage/review.html')

def games(request):
    return render(request, 'homepage/games.html')

def blog(request):
    return render(request, 'homepage/blog.html')

def contact(request):
    return render(request, 'homepage/contact.html')

def login(request):
    return render(request, 'homepage/login.html')

def register(request):
    message = ''
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            if Account.objects.filter(username=username).exists():
                message = "Tên tài khoản đã được sử dụng"
                return render(request, 'homepage/register.html', {'message':message})
            else:
                if Account.objects.filter(email=email).exists():
                    message = "Email đã được sử dụng"
                    return render(request, 'homepage/register.html', {'message':message})
                else:
                    user = Account(username=username, email=email, password=password)
                    user.save()
                    message = "Đăng ký thành công, hãy đăng nhập"
                    return render(request, 'homepage/register.html', {'message':message})
        else:
            message = "Mật khẩu không trùng khớp"
            return render(request, 'homepage/register.html', {'message':message})
    return render(request, 'homepage/register.html')

def login(request):
    message = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = Account.objects.filter(username=username,password=password)

        if user is not None:
            context = {
                'user':user,
                'username':username,
            }
            return render(request, 'homepage/index.html', context)
        else:
            message = "Tài khoản hoặc mật khẩu không đúng"
            context = {
                'message':message,
                'user':user,
            }
            return render(request,'homepage/login.html', context) 
    else:
       return render(request,'homepage/login.html')

def forgetpassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        user_mail = Account.objects.filter(email=email)
        characters = list('abcdefghijklmnopqrstuvwxyz')
        new_password = ''
        if user_mail.exists():
            for i in range(6):
                new_password += random.choice(characters)
            user_mail = Account(password=new_password)
            user_mail.save()
            subject = 'Typing-Game: Lấy lại mật khẩu'
            message = 'Mật khẩu mới của bạn là: '
            send_mail(subject, message, EMAIL_HOST_USER, [email], fail_silently = False)
            return render(request, 'homepage/login.html')
        else:
            message = "Email không tồn tại, hãy đăng ký tài khoản"
            return render(request, 'homepage/forget_password.html', {'message':message})
    return render(request, 'homepage/forget_password.html')

GameHome/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Typing Game</title>
		<meta charset="UTF-8">
		<meta name="description" content="EndGam Gaming Magazine Template">
		<meta name="keywords" content="endGam,gGaming, magazine, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Favicon -->
		<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>
	
		<!-- Google Font -->
		<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
	
	
		<!-- Stylesheets -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	
		<!-- Main Stylesheets -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
	
	</head>

	<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="home.html" class="site-logo">
					<img src="{% static 'img/logo.png' %}" alt="">
				</a>
				<nav class="top-nav-area w-100">
					<div class="user-panel">
						<a href="{% url 'GameHome:login' %}">Đăng nhập</a> / <a href="{% url 'GameHome:register' %}">Đăng ký</a>
					</div>
					<!-- Menu -->
					<ul class="main-menu primary-menu">
						<li><a href="{% url 'GameHome:index' %}">Trang chủ</a></li>
						<li><a href="{% url 'GameHome:review' %}">Giới thiệu</a></li>
						<li><a href="{% url 'GameHome:games' %}">Trò chơi</a>
							<ul class="sub-menu">
								<li><a href="game-single.html">Học tập</a></li>
								<li><a href="game-single.html">Luyện tập</a></li>
								<li><a href="game-single.html">Ôn tập</a></li>
							</ul>
						</li>
						<li><a href="{% url 'GameHome:blog' %}">Tin tức</a></li>
						<li><a href="{% url 'GameHome:contact' %}">Liên hệ</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header section end -->

	{% block blk %}
	{% endblock %}

	<!-- Newsletter section -->
	<section class="newsletter-section">
		<div class="container">
			<h2>Đăng ký nhận thông báo khi có bài viết mới</h2>
			<form class="newsletter-form">
				<input type="text" placeholder="Điền email của bạn vào đây">
				<button class="site-btn">Đăng ký <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<a href="#" class="footer-logo">
				<img src="{% static 'img/logo.png' %}" alt="">
			</a>
			<ul class="main-menu footer-menu">
				<li><a href="">Trang chủ</a></li>
				<li><a href="">Giới thiệu</a></li>
				<li><a href="">Trò chơi</a></li>
				<li><a href="">Tin tức</a></li>
				<li><a href="">Liên hệ</a></li>
			</ul>
			<div class="footer-social d-flex justify-content-center">
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<!-- <div class="copyright"><a href="">Colorlib</a> 2018 @ All rights reserved</div> -->
		</div>
	</footer>

	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>



    

GameHome/templates/homepage/blog.html
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>EndGam - Gaming Magazine Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/slicknav.min.css"/>
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="css/magnific-popup.css"/>
	<link rel="stylesheet" href="css/animate.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="index.html" class="site-logo">
					<img src="./img/logo.png" alt="">
				</a>
				<nav class="top-nav-area w-100">
					<div class="user-panel">
						<a href="">Login</a> / <a href="">Register</a>
					</div>
					<!-- Menu -->
					<ul class="main-menu primary-menu">
						<li><a href="index.html">Home</a></li>
						<li><a href="games.html">Games</a>
							<ul class="sub-menu">
								<li><a href="game-single.html">Game Singel</a></li>
							</ul>
						</li>
						<li><a href="review.html">Reviews</a></li>
						<li><a href="blog.html">News</a></li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header section end -->


	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="img/page-top-bg/3.jpg">
		<div class="page-info">
			<h2>Blog</h2>
			<div class="site-breadcrumb">
				<a href="">Home</a>  /
				<span>Blog</span>
			</div>
		</div>
	</section>
	<!-- Page top end-->


	<!-- Blog page -->
	<section class="blog-page">
		<div class="container">
			<div class="row">
				<div class="col-xl-9 col-lg-8 col-md-7">
					<ul class="blog-filter">
						<li><a href="#">Racing</a></li>
						<li><a href="#">Shooters</a></li>
						<li><a href="#">Strategy</a></li>
						<li><a href="#">Online</a></li>
					</ul>
					<div class="big-blog-item">
						<img src="img/blog-big/1.jpg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best VR games on the market</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="img/blog-big/2.jpg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="img/blog-big/3.jpg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="site-pagination">
						<a href="#" class="active">01.</a>
						<a href="#">02.</a>
						<a href="#">03.</a>
					</div>
				</div>
				<div class="col-xl-3 col-lg-4 col-md-5 sidebar">
					<div id="stickySidebar">
						<div class="widget-item">
							<form class="search-widget">
								<input type="text">
								<button>search</button>
							</form>
						</div>
						<div class="widget-item">
							<h4 class="widget-title">Trending</h4>
							<div class="trending-widget">
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="./img/blog-widget/1.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="./img/blog-widget/2.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="./img/blog-widget/3.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="./img/blog-widget/4.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<div class="categories-widget">
								<h4 class="widget-title">categories</h4>
								<ul>
									<li><a href="">Games</a></li>
									<li><a href="">Gaming Tips & Tricks</a></li>
									<li><a href="">Online Games</a></li>
									<li><a href="">Team Games</a></li>
									<li><a href="">Community</a></li>
									<li><a href="">Uncategorized</a></li>
								</ul>
							</div>
						</div>
						<div class="widget-item">
							<h4 class="widget-title">Latest Comments</h4>
							<div class="latest-comments">
								<div class="lc-item">
									<img src="./img/blog-widget/1.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="./img/blog-widget/2.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="./img/blog-widget/3.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="./img/blog-widget/4.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<a href="#" class="add">
								<img src="./img/add.jpg" alt="">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog page end-->


	<!-- Newsletter section -->
	<section class="newsletter-section">
		<div class="container">
			<h2>Subscribe to our newsletter</h2>
			<form class="newsletter-form">
				<input type="text" placeholder="ENTER YOUR E-MAIL">
				<button class="site-btn">subscribe <img src="img/icons/double-arrow.png" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="footer-left-pic">
				<img src="img/footer-left-pic.png" alt="">
			</div>
			<div class="footer-right-pic">
				<img src="img/footer-right-pic.png" alt="">
			</div>
			<a href="#" class="footer-logo">
				<img src="./img/logo.png" alt="">
			</a>
			<ul class="main-menu footer-menu">
				<li><a href="">Home</a></li>
				<li><a href="">Games</a></li>
				<li><a href="">Reviews</a></li>
				<li><a href="">News</a></li>
				<li><a href="">Contact</a></li>
			</ul>
			<div class="footer-social d-flex justify-content-center">
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="copyright"><a href="">Colorlib</a> 2018 @ All rights reserved</div>
		</div>
	</footer>
	<!-- Footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/jquery.sticky-sidebar.min.js"></script>
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/main.js"></script>

	</body>
</html>

GameHome/templates/homepage/login.html
{% extends "homepage/base.html" %}
{% load static %}
{% block blk %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    </head>

    <body>
	<section class="hero-section overflow-hidden">
		<div class="hero-slider owl-carousel">
			<div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="{% static 'img/slider-bg-1.jpg' %}">
                <form action="" class="login100-form validate-form" method="POST">
                    {% if message != "" %}
                    <div class="form-group" data-wow-delay="300ms">
                        <script>
                            var timer = setTimeout(function() {
                                $('#alert').fadeOut('slow');}, 5000);
                        </script>
                        <div id="alert" class="alert-success" style="padding: 10px; margin-bottom: 0px;">{{ message }}</div>
                    </div>
                    {% endif %}
                    {% csrf_token %}
                <div class="wrap-input100 validate-input" >
                    <input type="text" class="input100" placeholder="Nhập email" name="username" required>
                    <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                </div>
				<div class="wrap-input100 validate-input">
                    <input type="password" class="input100" name="password" placeholder="Nhập mật khẩu">
                    <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                </div>
                <div class="container-login100-form-btn">
                    <input type="submit" class="login100-form-btn" value="Đăng nhập"><br>
                </div>
                <p class="top30 mb-0"><a href="{% url 'GameHome:forgetpassword' %}" class="defaultcolor">Quên mật khẩu?</a></p>
                <p class="top30 mb-0"> Không có tài khoản? &nbsp;<a href="{% url 'GameHome:register' %}" class="defaultcolor">Đăng ký ngay</a> </p>
                </form>
			</div>
		</div>
	</section>
    </body>
{% endblock %}

GameHome/templates/homepage/register.html
{% extends "homepage/base.html" %}
{% load static %}
{% block blk %}

<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>

<body>
<section class="hero-section overflow-hidden">
    <div class="hero-slider owl-carousel">
        <div class="hero-item set-bg d-flex align-items-center justify-content-center text-center" data-setbg="{% static 'img/slider-bg-1.jpg' %}">
            <form class="ps-form--contact" action="" method="post">
                {% if message != "" %}
                <div class="form-group" data-wow-delay="300ms">
                    <script>
                        var timer = setTimeout(function() {
                            $('#alert').fadeOut('slow');}, 5000);
                    </script>
                    <div id="alert" class="alert-success" style="padding: 10px; margin-bottom: 0px;">{{ message }}</div>
                </div>
                {% elif message == "" %}
                <div></div>
                {% endif %}
                {% csrf_token %}
                <div class="form-group">
                    <label>Username <sup>*</sup></label>
                    <input class="input100" type="text" placeholder="Enter Your Username" name="username"
                        required>
                </div>
                <div class="form-group">
                    <label>Email <sup>*</sup></label>
                    <input class="input100" type="email" placeholder="Enter Your Email" name="email" required>
                </div>

                <div class="form-group">
                    <label>Password <sup>*</sup></label>
                    <input class="input100" type="password" placeholder="Enter Your Password" name="password"
                        required>
                </div>
                <div class="form-group">
                    <label>Confirm Password <sup>*</sup></label>
                    <input class="input100" type="password" placeholder="Confirm Password" name="confirm_password" required>
                </div>
                <div class="form-group">
                    <button class="login100-form-btn">Register </button>
                </div>
                <div class="form-group">
                    <div>
                        <p class="text-muted">Already An Account?<a class="ml-2" href="{% url 'GameHome:login' %}">Log In
                            </a></p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
</body>
{% endblock %}